name: blackbird
description: "A thologically indepth bible study app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  webview_flutter: ^4.13.0
  share_plus: ^11.0.0
  http: ^1.2.0
  html: ^0.15.6
  flutter_launcher_icons: ^0.13.1
  google_generative_ai: ^0.4.3
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.3+1
  speech_to_text: ^7.2.0
  flutter_tts: ^4.0.2
  audioplayers: ^6.5.0
  youtube_player_flutter: ^9.1.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/