// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFy-Od8j0S-o8d2yAw9lnyd6AW7JAOXQ0',
    appId: '1:135306016932:web:76933f47312fd1c8af8e31',
    messagingSenderId: '135306016932',
    projectId: 'bird-eye-7d52a',
    authDomain: 'bird-eye-7d52a.firebaseapp.com',
    storageBucket: 'bird-eye-7d52a.firebasestorage.app',
    measurementId: 'G-0489WZPYLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs403lcQgLbtXT13d679WyN_eaR2ez_90',
    appId: '1:135306016932:android:931d551096c5886eaf8e31',
    messagingSenderId: '135306016932',
    projectId: 'bird-eye-7d52a',
    storageBucket: 'bird-eye-7d52a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvW6Chj95gQVxAUa21oWmzSJ8IRC15VVY',
    appId: '1:135306016932:ios:983e8d50752d151faf8e31',
    messagingSenderId: '135306016932',
    projectId: 'bird-eye-7d52a',
    storageBucket: 'bird-eye-7d52a.firebasestorage.app',
    iosBundleId: 'com.josephoduyebo.blackbird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvW6Chj95gQVxAUa21oWmzSJ8IRC15VVY',
    appId: '1:135306016932:ios:7a152a3e4801f06baf8e31',
    messagingSenderId: '135306016932',
    projectId: 'bird-eye-7d52a',
    storageBucket: 'bird-eye-7d52a.firebasestorage.app',
    iosBundleId: 'com.example.blackbird',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFy-Od8j0S-o8d2yAw9lnyd6AW7JAOXQ0',
    appId: '1:135306016932:web:f8e241a1e8e17fe3af8e31',
    messagingSenderId: '135306016932',
    projectId: 'bird-eye-7d52a',
    authDomain: 'bird-eye-7d52a.firebaseapp.com',
    storageBucket: 'bird-eye-7d52a.firebasestorage.app',
    measurementId: 'G-G0SPTH15SR',
  );
}
